# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JSAN
version:      0.02
version_from: lib/JSAN.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0.19
    Class::DBI:                    0.96
    Class::DBI::DATA::Schema:      0.04
    Class::DBI::Loader:            0.22
    Class::DBI::Loader::SQLite:    0.22
    Class::DBI::SQLite:            0.09
    Cwd:                           3.01
    DBD::SQLite:                   1.09
    File::Path:                    1.06
    File::Temp:                    0.14
    Getopt::Long:                  2.34
    LWP::Simple:                   1.41
    SQL::Translator:               0.07
    Term::ReadLine:                1.01
    Test::Differences:             0.47
    Test::More:                    0.6
    YAML:                          0.39

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
